[package]
name = "tc2-frames"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.24.0"
raqote = "0.8.2"
font-kit = "0.11.0"
euclid = "0.22.9"
colorous = "1.0.10"
